services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "3000:3000"
    volumes:
      - ./main_app:/app
      - gem_cache:/usr/local/bundle

  worker:
    image: sweaty_wallet-web
    command: bundle exec sidekiq
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./main_app:/app
    depends_on:
      - web
  
  db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  gem_cache:
