FROM postgres:17.4-alpine

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        postgresql-17-pgvector \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get clean autoclean \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*

COPY ./init-db.d/ /docker-entrypoint-initdb.d/

