FROM ruby:3.3.6

WORKDIR /app

COPY ./main_app/Gemfile ./main_app/Gemfile.lock ./

RUN bundle install

RUN bundle exec rails tailwindcss:install

EXPOSE 3000

ENTRYPOINT ["bin/docker-entrypoint"]

CMD ["rails", "server", "-b", "0.0.0.0"]
