name: Linting
on:
  push:
    branches: "**"
jobs:
  rubocop:
    name: Runner / Rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: rubocop
        working-directory: ./main_app
        uses: reviewdog/action-rubocop@v1
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile rubocop-shopify:gemfile
          reporter: github-pr-review
          fail_on_error: true
