name: Linting
on:
  push:
    branches: "**"
jobs:
  rubocop:
    name: Runner / Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .tool-versions
          bundler-cache: true
          cache-version: ${{ secrets.CACHE_VERSION }}
      - name: rubocop
        uses: reviewdog/action-rubocop@v1
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile rubocop-shopify:gemfile
          reporter: github-pr-review
          fail_on_error: true
