# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Unit Tests"
on:
  push:
    branches: "**"
jobs:
  test:
    name: Runner / Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: pgvector/pgvector:0.8.0-pg17
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password

      redis:
        image: redis:alpine
        ports:
          - "6379:6379"
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: ./main_app
      - name: Set up database schema
        run: bin/rails db:schema:load
        working-directory: ./main_app
      - name: Run tests
        run: rspec
        working-directory: ./main_app

